{
    perform: true,
    commands: [
        {
            type: 'comment',
            name: 'needsMoreInfo',
            allowUsers: ['Tyriar', 'rebornix', 'sbatten', 'octref', 'roblourens', 'RMacfarlane', 'sana-ajani'],
            action: 'updateLabels',
            addLabel: 'needs more info',
            comment: "Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '~needs more info',
            action: 'updateLabels',
            addLabel: 'needs more info',
            removeLabel: '~needs more info',
            allowTriggerByBot: true,
            comment: "Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.\n\nHappy Coding!"
        },
    ]
}
