on:
  issue_comment:
    types: [created]
  issues:
    types: [opened,labeled]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Echoer
        uses: ./echoer
