on:
  schedule:
    - cron: "*"
  issue_comment:
    types: [created]
  issues:
    types: [opened,labeled]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/github-action-commands'
          ref: master # todo: change to tags once stabalized
      - name: Run Echoer
        uses: ./echoer
