name: Test Git
on: repository_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: master
          path: actions
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: repo
          depth: 0 # all
      - name: Run Locker
        uses: ./actions/author-verified
